---
name: Run mypy
on:
  pull_request:
  push:
    branches: ["main", "v[0-9]*"]
    tags: ["v[0-9]*"]
  workflow_dispatch:
jobs:
  mypy:
    runs-on: ubuntu-22.04
    steps:
      - name: apt update
        run: sudo apt update
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements-dev.txt
      - name: MyPy
        run: mypy .
